RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 2
CHUNK_SIZE: 500
CHUNK_OVERLAP: 50
DATA_PATH: 'data/'
DB_FAISS_PATH: 'vectorstore/db_faiss2'
# MODEL_TYPE: 'mpt'
MODEL_TYPE: 'llama'
MODEL_BIN_PATH: 'models/llama-2-7b-chat.ggmlv3.q4_0.bin' # 
#MODEL_BIN_PATH: 'models/llama-2-7b-chat.ggmlv3.q5_0.bin' # no mejoro la velocidad de respuesta
#MODEL_BIN_PATH: 'models/llama-2-7b-chat.ggmlv3.q8_0.bin'
#MODEL_BIN_PATH: 'models/llama-2-13b-chat.ggmlv3.q8_0.bin' # no pudo correr
MAX_NEW_TOKENS: 256
TEMPERATURE: 0.01